import os

PROJECT_DIR = "Research299"
COCO_DIR = os.path.join(PROJECT_DIR, "COCO")
RAW_COCO_DIR = os.path.join(COCO_DIR, "raw")
GENERATED_COCO_DIR = os.path.join(COCO_DIR, "generated")
DATA_DIR = os.path.join(COCO_DIR, "data")

# captions file
COCO_CAPTIONS_PATH = os.path.join(COCO_DIR, "test_captions.csv")

# Collected data file's path
FID_PATH = os.path.join(DATA_DIR,'fid_scores.csv')
CLIP_PATH = os.path.join(DATA_DIR,'clip_scores.csv')

# ID's
SD_MODEL_ID = "runwayml/stable-diffusion-v1-5"
CLIP_MODEL_ID = "openai/clip-vit-base-patch32"

# Inception Model's Weights used to calculate FID
INCEPT_WEIGHTS = "IMAGENET1K_V1"

# Diffusion Model's Parameters
SD_PARAMS = {
    "num_inference_steps": 20
}

# pipeline's params
BATCH_SIZE = 5

# minimumum amount of images needed to be generated by scheduler to evaluate
COCO_MIN_IMAGE_COUNT = 4500

# Hugging face scheduler labels
SCHEDULER_LABELS = ["ddpm", "pndm", "ddim", "unipc", "lms", "heun", "eds", "edm"]